version: '3'

services:

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - "27017:27017"
    volumes:
      - /home/fullzer4/Docker/Volumes/MongoDB:/data/db
    networks:
      - mongo-compose-network
  
networks: 
  mongo-compose-network:
    driver: bridge